version: "3.8"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: SUNU_MBAYE_MI
   
    ports:
      - "3306:3306"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_laravel
    restart: always
    depends_on:
      - database
    ports:
      - 8083:80
    environment:
      PMA_HOST: database
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_laravel
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_laravel
    ports:
      - "8092:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - dev

networks:
  dev:
